---
title: "HW2_solution and resampling"
author: '108048110'
date: "3/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HW2

```{r HW2}
plot_centrality <- function(data, title){
  plot(density(data))
  abline(v = mean(data))
  abline(v = median(data), lty="dashed")
}

d1 <- rnorm(n=500, mean=15, sd=5)
d2 <- rnorm(n=200, mean=30, sd=5)
d3 <- rnorm(n=100, mean=45, sd=5)
d123 <- c(d1, d2, d3)
plot_centrality(d123, 'Right positively skewed')

d123 <- rnorm(n=800)
plot_centrality(d123, 'Normal')

d1 <- rnorm(n=100, mean=5, sd=5)
d2 <- rnorm(n=200, mean=20, sd=5)
d3 <- rnorm(n=500, mean=35, sd=5)
d123 <- c(d1, d2, d3)
plot_centrality(d123, 'Left positively skewed')

quartile_vs_sd <- function(data, title){
  plot(density(data), main=title)
  abline(v=mean(data))
  sd_points <- mean(data)+(-3:3)*sd(data)
  abline(v=sd_points, lty="dashed")
  
  q <- quantile(data, c(0.25, 0.5, 0.75))
  return((q-mean(data))/sd(data))
}

r_default <- function(data){
  default_hist <- hist(data, col='lightgray')
  k <- length(default_hist$breaks)-2
  h <- (max(data)-min(data))/k
  return(data.frame(k, h))
}

rand_data <- rnorm(50000, mean=0, sd=1)
r_default(rand_data)
```

# Resampling

```{r}
seq_sample <- 1:22
resample <- sample(seq_sample, replace=TRUE)
re_sample <- c(1, rep(2,2), rep(3,3), rep(4,4), rep(5,3), rep(6,2), 7)
resample <- sample(re_sample, replace=TRUE)
plot(density(re_sample), lwd=3, prob = TRUE, ylim=c(0,0.25))
lines(density(resample), lty="dashed")
```

# USE THE UNSEEN POPULATION

```{r}
a <- rnorm(n=100000, mean=150, sd=15)
b <- rnorm(n=200000, mean=190, sd=25)
c <- rnorm(n=500000, mean=255, sd=25)
d <- rnorm(n=200000, mean=310, sd=20)
population = c(a, b, c, d)
pop_mean <- mean(population)

plot(density(population), lty='dashed', col="blue")
abline(v=pop_mean, lty="dashed")
```

# TAKE A SAMPLE FROM THE POPULATION

```{r}
sample_size <- 300
sample0 <- sample(population, sample_size)
sample0_mean <- mean(sample0)

plot(density(population), lty='dashed', col="blue")
abline(v=pop_mean, lty="dashed")
lines(density(sample0), col="blue", lwd=3)
abline(v = sample0_mean, lwd=3)
```

# RESAMPLE FROM OUR ORIGINAL POPULATION

```{r}
sample0

resample <- replicate(3000, sample(sample0, length(sample0), replace=TRUE))
plot(density(population), ylim=c(0, 0.009), lwd=0, main="Population vs. bootstrapped samples")

plt_resample_density <- function(sample_data){
  lines(density(sample_data), col=rgb(0.0, 0.4, 0.0, 0.01))
  return(mean(sample_data))
}

sample_means <- apply(resample, 2, FUN = plt_resample_density)
lines(density(sample0), lwd=3)
lines(density(population), lwd=2, lty='dashed')

plot(density(population), col="blue", lty='dashed')
lines(density(sample0), col="blue", lwd=2)
plt_resample_mean <- function(sample_data){
   abline(v=mean(sample_data), col=rgb(0.0, 0.4, 0.0, 0.01))
}
apply(resample, 2, plt_resample_mean)
abline(v = mean(sample_means), lwd=2)
abline(v = pop_mean, lty="dashed")

```

